require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GestorController do

  # This should return the minimal set of attributes required to create a valid
  # Gestor. As you add validations to Gestor, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "nome" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GestorController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all gestor as @gestor" do
      gestor = Gestor.create! valid_attributes
      get :index, {}, valid_session
      assigns(:gestor).should eq([gestor])
    end
  end

  describe "GET show" do
    it "assigns the requested gestor as @gestor" do
      gestor = Gestor.create! valid_attributes
      get :show, {:id => gestor.to_param}, valid_session
      assigns(:gestor).should eq(gestor)
    end
  end

  describe "GET new" do
    it "assigns a new gestor as @gestor" do
      get :new, {}, valid_session
      assigns(:gestor).should be_a_new(Gestor)
    end
  end

  describe "GET edit" do
    it "assigns the requested gestor as @gestor" do
      gestor = Gestor.create! valid_attributes
      get :edit, {:id => gestor.to_param}, valid_session
      assigns(:gestor).should eq(gestor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Gestor" do
        expect {
          post :create, {:gestor => valid_attributes}, valid_session
        }.to change(Gestor, :count).by(1)
      end

      it "assigns a newly created gestor as @gestor" do
        post :create, {:gestor => valid_attributes}, valid_session
        assigns(:gestor).should be_a(Gestor)
        assigns(:gestor).should be_persisted
      end

      it "redirects to the created gestor" do
        post :create, {:gestor => valid_attributes}, valid_session
        response.should redirect_to(Gestor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gestor as @gestor" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gestor.any_instance.stub(:save).and_return(false)
        post :create, {:gestor => { "nome" => "invalid value" }}, valid_session
        assigns(:gestor).should be_a_new(Gestor)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Gestor.any_instance.stub(:save).and_return(false)
        post :create, {:gestor => { "nome" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested gestor" do
        gestor = Gestor.create! valid_attributes
        # Assuming there are no other gestor in the database, this
        # specifies that the Gestor created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Gestor.any_instance.should_receive(:update_attributes).with({ "nome" => "MyString" })
        put :update, {:id => gestor.to_param, :gestor => { "nome" => "MyString" }}, valid_session
      end

      it "assigns the requested gestor as @gestor" do
        gestor = Gestor.create! valid_attributes
        put :update, {:id => gestor.to_param, :gestor => valid_attributes}, valid_session
        assigns(:gestor).should eq(gestor)
      end

      it "redirects to the gestor" do
        gestor = Gestor.create! valid_attributes
        put :update, {:id => gestor.to_param, :gestor => valid_attributes}, valid_session
        response.should redirect_to(gestor)
      end
    end

    describe "with invalid params" do
      it "assigns the gestor as @gestor" do
        gestor = Gestor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gestor.any_instance.stub(:save).and_return(false)
        put :update, {:id => gestor.to_param, :gestor => { "nome" => "invalid value" }}, valid_session
        assigns(:gestor).should eq(gestor)
      end

      it "re-renders the 'edit' template" do
        gestor = Gestor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Gestor.any_instance.stub(:save).and_return(false)
        put :update, {:id => gestor.to_param, :gestor => { "nome" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gestor" do
      gestor = Gestor.create! valid_attributes
      expect {
        delete :destroy, {:id => gestor.to_param}, valid_session
      }.to change(Gestor, :count).by(-1)
    end

    it "redirects to the gestor list" do
      gestor = Gestor.create! valid_attributes
      delete :destroy, {:id => gestor.to_param}, valid_session
      response.should redirect_to(gestor_index_url)
    end
  end

end
